### ISSUE TITLE
Insufficient Memory for the JRE

### ISSUE THREAD

**Issue by wal31** [aws/aws-sdk-java#1689]
Hi so i'm trying to loop through an s3 bucket that has over 500,000 files but i keep getting a JRE memory error. The main goal is to parse the files to string format and perform some operations on them. This is the loop:
try {
ListObjectsV2Request req = new ListObjectsV2Request().withBucketName(Config.getbucketName())
					.withMaxKeys(1000);
ListObjectsV2Result result;
int i = 1;
do {
	result = Config.gets3().listObjectsV2(req);
	System.out.println("ok. Now processing " + i + " batch of objects");
	for (S3ObjectSummary objectSummary : result.getObjectSummaries()) {
                 send to the approprite parse depending on the file extension
        add parsed texts to s3 bucket
         }
String token = result.getNextContinuationToken();
				System.out.println("Next Continuation Token: " + token);
				req.setContinuationToken(token);
			} while (result.isTruncated());
}catch(exception e)

I'm also getting a not all bytes read warning but I don't know how to get around that because the warning gets triggered when i do: 	document = new HWPFDocument(inputstream);

**Comment by shorea** [comment]
Can you provide a full code sample?

**Comment by wal31** [comment]
public class Parse {
	private static String[] data; // list of string arrays holding the value of text
									// to be written to the csv file
	private static HashMap<String, Integer> map = new HashMap<String, Integer>();
	private static String oldDir = " ";

	/**
	 * Iterates through the bucket and gets the object summaries to be processed
	 * 
	 * @param writer
	 */
	public static void iterate(CSVWriter writer) {
		try {

			ListObjectsV2Request req = new ListObjectsV2Request().withBucketName(Config.getbucketName())
					.withMaxKeys(1000);
			ListObjectsV2Result result;
			int i = 1;
			do {
				result = Config.gets3().listObjectsV2(req);
				System.out.println("ok. Now processing " + i + " batch of objects");
				for (S3ObjectSummary objectSummary : result.getObjectSummaries()) {
					String dir = regExp.candidate_id(objectSummary.getKey());// get the candidate_id
					if (dir == null)
						continue;
					if (!oldDir.equals(dir)) {
						map = new HashMap<String, Integer>();
					}
					if (dir != null) {
						if (objectSummary.getKey().toLowerCase().contains("cover_letter")) {
							map.put(dir, 1);
						} else {
							if (map.get(dir) == null)
								map.put(dir, 0);
							if (objectSummary.getKey().toLowerCase().contains("_resume")) {
								parseToText(objectSummary.getKey());
								Csv.write(writer);
							}
						}
					}
					oldDir = dir;
				}
				
				i++;
				Config.addTobucket();
				writer = new CSVWriter(new FileWriter(Csv.getCsvFile()), CSVWriter.DEFAULT_SEPARATOR,
						CSVWriter.NO_QUOTE_CHARACTER, CSVWriter.DEFAULT_ESCAPE_CHARACTER, CSVWriter.DEFAULT_LINE_END);
				Csv.open(writer);

				String token = result.getNextContinuationToken();
				System.out.println("Next Continuation Token: " + token);
				req.setContinuationToken(token);
			} while (result.isTruncated());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Calls the appropriate parser depending on the extension of the file
	 * 
	 * @param fname
	 *            holds the file path in the s3 bucket
	 * @param input
	 *            holds the input stream of the resume
	 * @throws IOException
	 */
	@SuppressWarnings("all")
	public static void parseToText(String fname) throws IOException {

		if (fname.toLowerCase().endsWith(".doc")) {
			docParse(fname);
		} else if (fname.toLowerCase().endsWith(".pdf")) {
			pdfParse(fname);
		} else if (fname.toLowerCase().endsWith(".docx")) {
			docxParse(fname);
		} else if (fname.toLowerCase().endsWith(".txt")) {
			txtParse(fname);

		} else // I noticed that there were some '.rtf' files
			System.out.println("not '.txt' '.pdf' '.doc' '.docx' file");

	}

	/**
	 * Parses '.doc' extension files
	 * 
	 * @param fname
	 *            holds the name of the file
	 * @param input
	 *            holds the input stream of the doc file
	 * @throws IOException
	 */
	@SuppressWarnings("all")
	private static void docParse(String fname) throws IOException {
		S3ObjectInputStream input = null;
		WordExtractor extractor = null;
		HWPFDocument document = null;
		S3Object object = Config.gets3().getObject(new GetObjectRequest(Config.getbucketName(), fname));
		try {
			input = object.getObjectContent();
			document = new HWPFDocument(input);
			extractor = new WordExtractor(document);
			String[] fileData = extractor.getParagraphText(); // get the text of the document
			String text = null;

			for (int i = 0; i < fileData.length; i++) {
				if (fileData[i] != null)
					text += fileData[i];
			}
			String resumetext = regExp.resumeText(text); // remove non alphanumeric characters
			String candidate_id = regExp.candidate_id(fname); // get the candidate_id from the key

			// add to the list if it's not null
			if (resumetext != null) {
				addToData(candidate_id, fname, resumetext, Integer.toString(getMap().get(candidate_id)));
			}
		} catch (Exception exep) {
			// exep.printStackTrace();
			input.abort();
		} finally {
			input.abort();
			input.close();
			object.close();
			if (extractor != null)
				extractor.close();
			if (document != null)
				document.close();
		}
	}

	/**
	 * Parses '.pdf' extension files
	 * 
	 * @param fname
	 *            holds the name of the file
	 * @param input
	 *            holds the input stream of the doc file
	 * @throws IOException
	 */
	@SuppressWarnings("all")
	private static void pdfParse(String fname) throws IOException {
		S3ObjectInputStream input = null;
		PDFTextStripper pdfStripper;
		PDDocument pdDoc = null;
		S3Object object = Config.gets3().getObject(new GetObjectRequest(Config.getbucketName(), fname));
		try {
			input = object.getObjectContent();
			pdDoc = PDDocument.load(input);
			pdfStripper = new PDFTextStripper();
			String text = pdfStripper.getText(pdDoc);

			String resumetext = regExp.resumeText(text); // remove non alphanumeric characters
			String candidate_id = regExp.candidate_id(fname); // get the candidate_id from the key

			// add to the list if it's not null
			if (resumetext != null) {
				addToData(candidate_id, fname, resumetext, Integer.toString(getMap().get(candidate_id)));
			}
		} catch (Exception e) {
			// e.printStackTrace();
		} finally {
			input.abort();
			input.close();
			object.close();
			if (pdDoc != null)
				pdDoc.close();
		}

	}

	/**
	 * Parses '.docx' extension files
	 * 
	 * @param fname
	 *            holds the name of the file
	 * @param input
	 *            holds the input stream of the doc file
	 * @throws IOException
	 */
	@SuppressWarnings("all")
	private static void docxParse(String fname) throws IOException {
		S3ObjectInputStream input = null;
		XWPFDocument xdoc = null;
		XWPFWordExtractor extractor = null;
		S3Object object = Config.gets3().getObject(new GetObjectRequest(Config.getbucketName(), fname));
		try {
			input = object.getObjectContent();
			xdoc = new XWPFDocument(OPCPackage.open(input));
			extractor = new XWPFWordExtractor(xdoc);
			object.close();
			String extractedText = extractor.getText();
			String resumetext = regExp.resumeText(extractedText); // remove non alphanumeric characters
			String candidate_id = regExp.candidate_id(fname); // get the candidate_id from the key

			// add to the list if it's not null
			if (resumetext != null) {
				addToData(candidate_id, fname, resumetext, Integer.toString(getMap().get(candidate_id)));
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			input.abort();
		} finally {
			input.abort();
			input.close();
			object.close();
			if (xdoc != null)
				xdoc.close();
			if (extractor != null)
				extractor.close();
		}
	}

	/**
	 * Parses '.txt' extension files
	 * 
	 * @param fname
	 *            holds the name of the file
	 * @param input
	 *            holds the input stream of the doc file
	 * @throws IOException
	 */
	@SuppressWarnings("all")
	private static void txtParse(String fname) throws IOException {
		S3ObjectInputStream input = null;
		String text = ""; // handles the inconvenience of using readline to read the '.txt' files
		BufferedReader reader = null;
		S3Object object = Config.gets3().getObject(new GetObjectRequest(Config.getbucketName(), fname));
		try {
			input = object.getObjectContent();
			reader = new BufferedReader(new InputStreamReader(input));
			while (true) {
				String line = reader.readLine();

				if (line == null)
					break;

				text += line;
			}
			String resumetext = regExp.resumeText(text); // remove non alphanumeric characters

			// add to the list if it's not null
			if (resumetext != null) {
				String candidate_id = regExp.candidate_id(fname); // get the candidate_id from the key
				addToData(candidate_id, fname, resumetext, Integer.toString(getMap().get(candidate_id)));
			}
		} catch (Exception e) {

		} finally {
			input.abort();
			input.close();
			object.close();
			if (reader != null)
				reader.close();
		}
	}

	/**
	 * Extracts the <i>Experience</i> section of the resume
	 * 
	 * @param resumetext
	 *            holds the parsed text of the resume
	 * @return the experience section
	 */
	public static String getExperience(String resumetext) {
		String experience = regExp.getKeyword("Experience", resumetext);
		String spaceExp = regExp.getKeyword("E X P E R I E N C E", resumetext);
		String capsExp = regExp.getKeyword("EXPERIENCE", resumetext);
		String employment = regExp.getKeyword("Employment", resumetext);
		String capsEmployment = regExp.getKeyword("EMPLOYMENT", resumetext);
		String careerHist = regExp.getKeyword("Career History", resumetext);

		return regExp.removedates(experience + employment + spaceExp + capsExp + capsEmployment + careerHist);
	}

	/**
	 * Extracts the <i>Education</i> section of the resume
	 * 
	 * @param resumetext
	 *            holds the parsed text of the resume
	 * @return the education section
	 */
	public static String getEducation(String resumetext) {

		String education = regExp.getKeyword("Education", resumetext);
		String capsEdu = regExp.getKeyword("EDUCATION", resumetext);
		String schoolHist = regExp.getKeyword("School History", resumetext);
		String smallHist = regExp.getKeyword("school history", resumetext);
		String credentials = regExp.getKeyword("CREDENTIALS", resumetext);
		String spaceEdu = regExp.getKeyword("E D U C A T I O N", resumetext);
		String capsQual = regExp.getKeyword("QUALIFICATION", resumetext);
		String qual = regExp.getKeyword("Qualifications", resumetext);

		return education + capsEdu + schoolHist + smallHist + credentials + spaceEdu + capsQual + qual;
	}

	/**
	 * Extracts the <i>Skills</i> section of the resume
	 * 
	 * @param resumetext
	 *            holds the parsed text of the resume
	 * @return the skills section
	 */
	public static String getSkills(String resumetext) {
		String skills = regExp.getKeyword("Skills", resumetext);
		String capSkills = regExp.getKeyword("SKILLS", resumetext);
		String spaceSkills = regExp.getKeyword("S K I L L S", resumetext);

		return regExp.removedates(skills + capSkills + spaceSkills);
	}

	/**
	 * Calls the appropriate function to extract the different sections of the
	 * resume and then writes the field to a row represented by a list of string
	 * arrays
	 * 
	 * @param candidate_id
	 *            holds the candidate ID
	 * @param fname
	 *            holds the file path on S3
	 * @param resumetext
	 *            Parsed resume text
	 * @param coverLetter
	 *            holds the information on weather the candidate has a cover letter
	 */
	public static void addToData(String candidate_id, String fname, String resumetext, String coverLetter) {
		String skills = getSkills(resumetext);
		String experience = getExperience(resumetext);
		String education = getEducation(resumetext);
		data = new String[] { candidate_id, fname, resumetext, Integer.toString(getMap().get(candidate_id)), experience,
				education, skills };
	}

**Comment by shorea** [comment]
I don't see anything immediately wrong. Looks like you are closing the input stream properly from GetObject. Can you try with the latest SDK regarding the log warning, we just pushed a fix to address that issue. As far as the OOM error, do you know where it's leaking memory? Can you attach a profiler to see the memory hotspots?

**Comment by shorea** [comment]
Do you mean 1.11.372? If so then yes that's the latest.

**Comment by wal31** [comment]
the warning is still happening. also i'm gonna see if it's my ec2 ram space cause I haven't seen the error when testing locally

**Comment by wal31** [comment]
hey it was my ec2 ram space, thank you for your help!!!
