### ISSUE TITLE
Endless loop of AbortedException from AmazonSQSClient.receiveMessage on client execution timeout

### ISSUE THREAD

**Issue by kristwaa** [aws/aws-sdk-java#1776]
I'm seeing intermittent occurrences of an endless loop of stacktraces with AbortedException when polling messages from an SQS queue. This typically results in the disk being filled, and / or high CPU usage, bringing the system to a halt.
Stacktrace:

    [simpleMessageListenerContainer-1] WARN org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer - An Exception occurred while polling queue 'snipped'. The failing operation will be retried in 10000 milliseconds
    com.amazonaws.http.timers.client.ClientExecutionTimeoutException: Client execution did not complete before the specified timeout configuration.
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException(AmazonHttpClient.java:806)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:703)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1380)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1356)
        at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    [simpleMessageListenerContainer-1] WARN org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer - An Exception occurred while polling queue 'snipped'. The failing operation will be retried in 10000 milliseconds
    com.amazonaws.AbortedException: 
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException(AmazonHttpClient.java:809)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:703)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1380)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1356)
        at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: com.amazonaws.http.timers.client.SdkInterruptedException
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:856)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:842)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1036)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
        ... 14 more
    [simpleMessageListenerContainer-1] WARN org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer - An Exception occurred while polling queue 'snipped'. The failing operation will be retried in 10000 milliseconds
    com.amazonaws.AbortedException: 
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException(AmazonHttpClient.java:809)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:703)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1380)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1356)
        at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: com.amazonaws.http.timers.client.SdkInterruptedException
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:856)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:842)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1036)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
        ... 14 more
        .... < repeates forever >

This was originally observed on a legacy system using AWS SDK for Java 1.11.125, but the stacktrace above is a provoked stacktrace from 1.11.421.
Java version:
> java version "1.8.0_172"
> Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

This may be a problem only when the SDK is used together with Spring, more specifically `SimpleMessageListenerContainer` from spring-cloud-aws, but I'm hoping to get some feedback from people knowing the internals of `AmazonHttpClient`.

The system in question runs without problems for days, then suddenly the above happens. Timeouts have been set, and many of the timeouts have the same value (client execution, request, socket). I was unable to reproduce the error when not messing with the state, but by code inspection I saw a potential race condition. Unfortunately one piece is in `AmazonHttpClient` and the other piece in `SimpleMessageListenerContainer`. Assume the following code is run ([source](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L797)):

         private RuntimeException handleInterruptedException(InterruptedException e) {
            if (e instanceof SdkInterruptedException) {
                if (((SdkInterruptedException) e).getResponse() != null) {
                    ((SdkInterruptedException) e).getResponse().getHttpResponse().getHttpRequest().abort();
                }
            }
            if (executionContext.getClientExecutionTrackerTask().hasTimeoutExpired()) {
                // Clear the interrupt status
                Thread.interrupted(); // POINT (A)
                return new ClientExecutionTimeoutException();
            } else {
                Thread.currentThread().interrupt(); // POINT (B)
                return new AbortedException(e);
            }
        }

Followed by ([source](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L299)):

                    try {
                        //noinspection BusyWait
                        Thread.sleep(getBackOffTime()); // POINT (C)
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt(); // POINT (D)
                    }
                }

In a debugger I made the client request to the queue time out by setting the wait period higher than the client execution timeout. This brings the code to _(A)_, the exception is thrown and we continue to _(C)_. The thread goes to sleep for 10 seconds and the polling is retried after that period. All good.

In the debugger I brought the code to _(A)_. After stepping over that line, clearing the interrupt status, I manually interrupted the thread again. Resuming operation, the code got to _(C)_. The `Thread.sleep`-command immediately throws an InterruptedException, and at _(D)_ the thread is interrupted again (according to good practice, given no other useful actions is taken). When the code returns to `AmazonHttpClient.handleInterruptedException` false is returned by `executionContext.getClientExecutionTrackerTask().hasTimeoutExpired()` and the code gets to _(B)_ where the thread is interrupted. We get to _(C)_ again, and the endless loop is a fact.

1. Do you see possibilities for the above happening during normal operation?
  (bug, timing issues, misconfiguration)
1. Can setting multiple timeouts to the same value result in the Java thread being interrupted more than once?
  (race condition, intermittent error, possibly mechanisms initiated lower in the stack?)
1. What have I overlooked? :)

**Comment by kristwaa** [comment]
Happened again today, generated ~110 GB of log in a relatively short amount of time. Recovered by restarting the Java process.

In an attempt to avoid the problem, I have reconfigured the timeout values such that they differ with half a second (`withSocketTimeout`, `withRequestTimeout`, `withClientExecutionTimeout`).

**Comment by zoewangg** [comment]
Apologies for the delayed response. Looks like the issue was that the interrupt status was not correctly cleared. We've made a fix for the similar situation in some edge cases. More specifically, adding this line in `handleAbortedException` method:
https://github.com/aws/aws-sdk-java/blob/65813828d79953d6120ce75802696577aae0863e/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L824-L826

to clear the interrupt status if the abortedException is caused by the timer. This fix is available in `1.11.317` and the versions after. Could you try to upgrade the SDK version?

Setting `socketTImeout`, `requestTimeout` and `clientExecutionTimeout` to the same value should not causing thread being interrupted more than once as only `clientExecutionTimeout` would interrupt the thread. (It's not recommended to set them to the same value though as [clientExecutionTimeout](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#getClientExecutionTimeout--) includes all retries.)

**Comment by kristwaa** [comment]
Thank you for the response, @zoewangg.

This is a legacy application where it's not straight forward to upgrade the library. I provoked the bug with `1.11.421`, which is why I'm somewhat skeptical that upgrading will solve the problem. But I will give it a try.


I did notice the change when checking the versions, but during debugging it was never reached.
The problem may be that the interrupt status for some reason has escaped the SDK domain, as described by line 712: https://github.com/aws/aws-sdk-java/blob/65813828d79953d6120ce75802696577aae0863e/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L709-L713. 

Then a new request is attempted with the interrupt status set on the thread. I suspect the `SdkInterruptedException` is thrown in the first iteration of the `while (true)`-loop (line 1035):

    Caused by: com.amazonaws.http.timers.client.SdkInterruptedException
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:856)
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:842)
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1036)
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
  	  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
  	  ... 14 more

At this point `executionContext.getClientExecutionTrackerTask().hasTimeoutExpired())` returns `false`, which leads to not clearing the interrupted flag, but rather setting it again on line 808:
https://github.com/aws/aws-sdk-java/blob/65813828d79953d6120ce75802696577aae0863e/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L797-L811

The above assumption is strengthened by the following code (from Spring, [source](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L278-L309)) resulting in back-to-back execution instead of a pause:

                    try {
                        //noinspection BusyWait
                        Thread.sleep(getBackOffTime());
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                    }

Of course, the missing piece here is how we end up in this situation.

**Comment by zoewangg** [comment]
Yeah, we did pushed out a fix to prevent stale read on `executionContext.getClientExecutionTrackerTask().hasTimeoutExpired()` and that seems the same issue you are seeing here. 

That fix is available from `1.11.242`. Please let us know if you continue seeing the issue after upgrading.

**Comment by kristwaa** [comment]
Now running `1.11.421` (with some really old Spring-stuff on top). Will create a new issue if it happens again.

Thank you for your patience with a "slow upgrader" :)

**Comment by kristwaa** [comment]
Unfortunately this happens also with version `1.11.421`. Reopening.

No further clues as to why the interrupted flag of the thread isn't cleared.

**Comment by zoewangg** [comment]
Going to go ahead and close the issue as there is no more information available to debug further. Feel free to reopen if you continue seeing the errors in your new process.

**Comment by amrmhmohamed** [comment]
I'm seeing this issue on 1.11.267. Same behavior as OP. Once we hit it once, we hit it forever. I have to kill the JVM.

`com.amazonaws.AbortedException: 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException(AmazonHttpClient.java:795)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
  at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2013)
  at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1989)
  at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1471)
  at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1447)
  at com.s.m.d.i.common.queue.SQSQueue.waitForMessage(SQSQueue.java:83)
  at com.s.m.d.i.m.IQH.processISQSMessages(IQH.java:68)
  at com.s.m.d.i.m.IQH.run(IQH.java:39)
  at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.http.timers.client.SdkInterruptedException: null
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:840)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:826)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1019)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
  ... 11 common frames omitted`

**Comment by zoewangg** [comment]
@amrmhmohamed Hi, we found a race condition in the SDK where the execution timer interrupts the thread at the same time the response is complete or an exception is thrown, leaving the interrupt flag uncleared.

We have pushed out a fix in `1.11.698` https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111698-2019-12-20 

Can you try with the latest version?

**Comment by amrmhmohamed** [comment]
Unfortunately I am bound to our company's third party library review process before I can try with the latest version.

From your knowledge of the issue and what you did to resolve it. Can I work around this issue by instantiating a new AmazonSQS object and using that instead? Or is the flag not tied to this object and I will still see the issue.

**Comment by dagnir** [comment]
Unfortunately, instantiating a new client will not resolve the issue since the interrupted flag is maintained within the Thread's context, not within the SDK client.

**Comment by amrmhmohamed** [comment]
Ok, thanks for that info, it's good to know. So if I wanted to go as far as killing the thread I'm in and restarting it, then reusing the same AmazonSQS object should be fine?

**Comment by dagnir** [comment]
Yes that could be one solution. As another workaround, you can also call [`Thread.interrupted()`](https://docs.oracle.com/javase/6/docs/api/java/lang/Thread.html#interrupted()) before calling the client method to clear the interrupted flag yourself.

**Comment by amrmhmohamed** [comment]
That sounds a lot simpler. Can I call Thread.interrupted() conditionally if I catch the AbortedException then retry?

**Comment by dagnir** [comment]
Yep that should work.

**Comment by amrmhmohamed** [comment]
Nothing substantial to report. We finally upgraded past 698, and we haven't seen the issue. But it was only happening for us when the number of in-flight messages was in the 50k range due to another defect that we now fixed. I don't have time to simulate the issue again in dev to test. I think we're good, though.

**Comment by aamirraza** [comment]
even after upgrading to version 1.11.698, we are still getting 

Exception encountered in firing notifications in processRescheduleSettlementsWithAvailableTime() {} au.necdl.pexa.exception.ApplicationException: com.amazonaws.http.timers.client.ClientExecutionTimeoutException: Client execution did not complete before the specified timeout configuration.
	at deployment.pexa_web.war//au.necdl.pexa.core.lobs.LobsS3Service.putS3ObjectBinary(LobsS3Service.java:76)
	at deployment.pexa_web.war//au.necdl.pexa.core.lobs.LobsS3Service$$FastClassBySpringCGLIB$$6411373a.invoke(<generated>)
	at deployment.pexa_web.war//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at deployment.pexa_web.war//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at deployment.pexa_web.war//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at deployment.pexa_web.war//org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at deployment.pexa_web.war//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at deployment.pexa_web.war//org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)

**Comment by PRASANTHRAJENDRAN** [comment]
I am getting the same issue with the version `1.11.939`, my simple use case. I have 300 messages in my FIFO SQS queue and I am polling a max limit of 10 messages per time until I read all messages from the queue, Initially, for the first 80 messages it was going smooth but getting the below exception after that

**Code to read a message from FIFO queue**
```
        boolean hasNext;
        do {
            ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest()
                    .withQueueUrl("<queueUrl>")
                    .withWaitTimeSeconds(5)
                    .withMessageAttributeNames("All")
                    .withVisibilityTimeout(30)
                    .withMaxNumberOfMessages(10);
            ReceiveMessageResult receiveMessageResult = amazonSQS.receiveMessage(receiveMessageRequest);
            hasNext = !receiveMessageResult.getMessages().isEmpty() && receiveMessageResult.getMessages().size() >= 10;
        } while (hasNext);
```
     
**Exception**


```
com.amazonaws.AbortedException: 
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException(AmazonHttpClient.java:868)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:746)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2243)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2210)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2199)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeDeleteMessage(AmazonSQSClient.java:910)
	at com.amazonaws.services.sqs.AmazonSQSClient.deleteMessage(AmazonSQSClient.java:881)
	at com.amazonaws.services.sqs.AmazonSQSClient.deleteMessage(AmazonSQSClient.java:922)
	at com.trimble.connect.services.events.common.configuration.AWSSQSOperations.deleteMessage(AWSSQSOperations.java:294)
	at com.trimble.connect.services.events.processor.service.EventsQueueProcessorService.lambda$processEventsInEventTypeQueue$1(EventsQueueProcessorService.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.trimble.connect.services.events.processor.service.EventsQueueProcessorService.processEventsInEventTypeQueue(EventsQueueProcessorService.java:191)
	at com.trimble.connect.services.events.processor.service.EventsQueueProcessorService.receiveMessagesFromEventType(EventsQueueProcessorService.java:182)
	at com.trimble.connect.services.events.processor.service.EventsQueueProcessorService.processEventTypeQueueMessage(EventsQueueProcessorService.java:120)
	at com.trimble.connect.services.events.processor.schedule.EventsQueueProcessorExecutor.task(EventsQueueProcessorExecutor.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.http.timers.client.SdkInterruptedException: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:923)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:909)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1103)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	... 30 common frames omitted

```
