### ISSUE TITLE
header parsing should be case insensitive

### ISSUE THREAD

**Issue by jackphel** [aws/aws-sdk-java#449]
I'm opening this again because it's a huge pain in the neck for me. Maybe someone can do this as a quick onboarding task to make a little change then get all the tests to run?

Node and Webrick expect and force case insensitive headers. I submitted a patch to #436 and tests broke. I couldn't see which tests.

I'm using https://github.com/jubos/fake-s3 as an offline server for development and testing, but because https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/ObjectMetadata.java#L625 is only looking for the capitalized version of the header, it misses the "etag" header that this dev server always returns as all lowercase.

**Comment by andrewgaul** [comment]
You can use [Chaos HTTP Proxy](https://github.com/bouncestorage/chaos-http-proxy) to change the case name of headers and flush out all the incorrect case comparisons.

**Comment by jtwaleson** [comment]
+1, also suffering from this issue with RiakCS behind haproxy

**Comment by shorea** [comment]
We've merged some changes that should alleviate some of this pain. These changes will be included in the next release of the SDK tentatively scheduled for later this week. I'll update the issue when it's officially available. 

https://github.com/aws/aws-sdk-java/pull/590

**Comment by shorea** [comment]
This has been released. Let us know if there are any other ways we can improve our compliance with the HTTP spec.

**Comment by l15k4** [comment]
It didn't seem to fix this problem. I use aws-java-sdk-s3 1.11.46 : 
```
com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 1B2M2Y8AsgTpgAmY7PhCfg== in base 64) didn't match hash (etag: 1ffb5f1a9da76e430021d693a85d988b in hex) calculated by Amazon S3.
```
